letters<-read.csv('letters_ABPR.csv')
letters$isB = as.factor(letters$letter == "B")
library(caTools)
set.seed(1000)
split_letters = sample.split(letters$isB,SplitRatio = 0.5)
Train_Letters = subset(letters,split_letters==TRUE)
Test_Letters  = subset(letters,split_letters==FALSE)
table(Train_Letters$isB)
table(Test_Letters$isB)
1175/nrow(Test_Letters)
CARTb = rpart(isB ~ . - letter, data=Train_Letters, method="class")
Predictb =predict(CARTb,newdata = Test_Letters, type="class")
table(Test_Letters$isB,Predictb)
(1118+340)/nrow(Test_Letters)


set.seed(1000)
library(randomForest)
Forrestb=randomForest(isB ~ . - letter, data=Train_Letters)
PredictForrestb = predict(Forrestb,newdata = Test_Letters)
table(Test_Letters$isB,Predictb)
letters$letter = as.factor( letters$letter )
set.seed(1000)
split_letters_2 = sample.split(letters$letter,SplitRatio = 0.5)
Train_Letters_2 = subset(letters,split_letters_2==TRUE)
Test_Letters_2  = subset(letters,split_letters_2==FALSE)
#Accuracy of the baseline model(401 for P is the most repated obs)
401/nrow(Test_Letters_2)

TreeL <- rpart(letter ~ . -isB,data = Train_Letters_2,method = "class")
PredTreeL <- predict(TreeL,newdata=Test_Letters_2,type="class")
table(Test_Letters_2$letter,PredTreeL)
(376+318+367+350)/nrow(Test_Letters_2)
