# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "tomoe-desktop-mint-5.0.0"
  config.vm.box_url = "http://140.203.155.53:7070/tomoe-desktop-mint/version/5.0.0/virtualbox/tomoe-desktop-mint-5.0.0-virtualbox.box"

  config.vm.synced_folder "C:\Users\Bijith\Documents\Sources", "/home/vagrant/host/project"
  config.vm.synced_folder "C:\Users\Bijith\ownCloud", "/home/vagrant/host/ownCloud"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "tomoe-desktop-mint-5.0.0"
    vb.gui = true
    vb.memory = 4096
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

end