airline=read.csv('C://myRepo//R//FL-Airline_Data//2008.csv')

headrnorm(200)
head(airline$Origin == 'IND')
sum(airline$Origin == 'IND')
sum(airline$Origin == 'ORD')
sum(airline$Dest == 'ORD')
sum( (airline$Origin == 'IND') & (airline$Dest == 'ORD') )
myIndieFlights <- subset(airline,airline$Origin=='IND')
myIndieDest <- subset(airline,airline$Dest=='IND')
plot(table(myIndieFlights$Month))
myTupFlights <- subset(airline,airline$Origin=='TUP')
mean(myTupFlights$DepDelay)
head(myIndieFlights)
sum(myIndieFlights$DepTime<600,na.rm = TRUE)
