LIBNAME mydata "/courses/d1406ae5ba27fe300 " access=readonly;
DATA new; set mydata.nesarc_pds;
LABEL TAB12MDX="Tobacco Dependence Past 12 Months"
	  CHECK321="Smoked Cigarettes in Past 12 Months"
	  S3AQ3B1="Usual Smoking Frequency"
	  S3AQ3C1="Usual Smoking Quantity";

/*Set appropriate missing data as needed*/
IF S3AQ3B1=9 THEN S3AQ3B1=.;
IF S3AQ3C1=99 THEN S3AQ3C1=.;

IF S3AQ3B1=1 THEN USFREQMO=30;
ELSE IF S3AQ3B1=2 THEN USFREQMO=22;
ELSE IF S3AQ3B1=3 THEN USFREQMO=14;
ELSE IF S3AQ3B1=4 THEN USFREQMO=5;
ELSE IF S3AQ3B1=5 THEN USFREQMO=2.5;
ELSE IF S3AQ3B1=6 THEN USFREQMO=1;
/*USFREQMO usual smoking days per month
1=once a month or less
2.5=2-3 days per month
5=1-2 days per week 
14=3-4 days per week
22=5-6 days per week
30=everyday*/

NUMCIGMO_EST=USFREQMO*S3AQ3C1;

PACKSPERMONTH=NUMCIGMO_EST/20;

IF PACKSPERMONTH LE 5 THEN PACKCATEGORY=3;
ELSE IF PACKSPERMONTH LE 10 THEN PACKCATEGORY=7;
ELSE IF PACKSPERMONTH LE 20 THEN PACKCATEGORY=15;
ELSE IF PACKSPERMONTH LE 30 THEN PACKCATEGORY=25;
ELSE IF PACKSPERMONTH GT 30 THEN PACKCATEGORY=58;

/*subsetting data to include only past 12 month smokers, age 18-25*/
IF CHECK321=1;
IF AGE LE 25;

PROC SORT; by IDNUM;

/*PROC ANOVA; CLASS ETHRACE2A;
MODEL NUMCIGMO_EST=ETHRACE2A;
MEANS ETHRACE2A/DUNCAN;*/

PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;

RUN;

DATA COMPARISON1; SET NEW;
IF USFREQMO=1 OR USFREQMO=2.5;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON2; SET NEW;
IF USFREQMO=1 OR USFREQMO=6;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON3; SET NEW;
IF USFREQMO=1 OR USFREQMO=14;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON4; SET NEW;
IF USFREQMO=1 OR USFREQMO=22;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON5; SET NEW;
IF USFREQMO=1 OR USFREQMO=30;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON6; SET NEW;
IF USFREQMO=2.5 OR USFREQMO=6;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON7; SET NEW;
IF USFREQMO=2.5 OR USFREQMO=14;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON8; SET NEW;
IF USFREQMO=2.5 OR USFREQMO=22;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON9; SET NEW;
IF USFREQMO=2.5 OR USFREQMO=30;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON10; SET NEW;
IF USFREQMO=6 OR USFREQMO=14;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON11; SET NEW;
IF USFREQMO=6 OR USFREQMO=22;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON12; SET NEW;
IF USFREQMO=6 OR USFREQMO=30;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON13; SET NEW;
IF USFREQMO=14 OR USFREQMO=22;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON1; SET NEW;
IF USFREQMO=14 OR USFREQMO=30;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;

DATA COMPARISON15; SET NEW;
IF USFREQMO=22 OR USFREQMO=30;
PROC SORT; BY IDNUM;
PROC FREQ; TABLES TAB12MDX*USFREQMO/CHISQ;
RUN;
